//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace picibird.hbs.resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class department {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal department() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("picibird.hbs.resources.department", typeof(department).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archaeology.
        /// </summary>
        internal static string _10 {
            get {
                return ResourceManager.GetString("10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art.
        /// </summary>
        internal static string _100 {
            get {
                return ResourceManager.GetString("100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mathematics.
        /// </summary>
        internal static string _110 {
            get {
                return ResourceManager.GetString("110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media &amp; Comm..
        /// </summary>
        internal static string _120 {
            get {
                return ResourceManager.GetString("120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine.
        /// </summary>
        internal static string _130 {
            get {
                return ResourceManager.GetString("130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        internal static string _140 {
            get {
                return ResourceManager.GetString("140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedagogy.
        /// </summary>
        internal static string _150 {
            get {
                return ResourceManager.GetString("150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Philosophy.
        /// </summary>
        internal static string _160 {
            get {
                return ResourceManager.GetString("160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physics.
        /// </summary>
        internal static string _170 {
            get {
                return ResourceManager.GetString("170", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Politics.
        /// </summary>
        internal static string _180 {
            get {
                return ResourceManager.GetString("180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psychology.
        /// </summary>
        internal static string _190 {
            get {
                return ResourceManager.GetString("190", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biology.
        /// </summary>
        internal static string _20 {
            get {
                return ResourceManager.GetString("20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Law.
        /// </summary>
        internal static string _200 {
            get {
                return ResourceManager.GetString("200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Religion.
        /// </summary>
        internal static string _210 {
            get {
                return ResourceManager.GetString("210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sociology.
        /// </summary>
        internal static string _220 {
            get {
                return ResourceManager.GetString("220", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sports.
        /// </summary>
        internal static string _230 {
            get {
                return ResourceManager.GetString("230", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language &amp; Literature.
        /// </summary>
        internal static string _240 {
            get {
                return ResourceManager.GetString("240", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology.
        /// </summary>
        internal static string _250 {
            get {
                return ResourceManager.GetString("250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Economy.
        /// </summary>
        internal static string _260 {
            get {
                return ResourceManager.GetString("260", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Science.
        /// </summary>
        internal static string _270 {
            get {
                return ResourceManager.GetString("270", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Sciences.
        /// </summary>
        internal static string _280 {
            get {
                return ResourceManager.GetString("280", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural Sciences.
        /// </summary>
        internal static string _290 {
            get {
                return ResourceManager.GetString("290", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book &amp; Infor. Science.
        /// </summary>
        internal static string _30 {
            get {
                return ResourceManager.GetString("30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemical.
        /// </summary>
        internal static string _40 {
            get {
                return ResourceManager.GetString("40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethnology.
        /// </summary>
        internal static string _50 {
            get {
                return ResourceManager.GetString("50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geography.
        /// </summary>
        internal static string _60 {
            get {
                return ResourceManager.GetString("60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geology.
        /// </summary>
        internal static string _70 {
            get {
                return ResourceManager.GetString("70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string _80 {
            get {
                return ResourceManager.GetString("80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer Science.
        /// </summary>
        internal static string _90 {
            get {
                return ResourceManager.GetString("90", resourceCulture);
            }
        }
    }
}
