//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace picibird.hbs.resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("picibird.hbs.resources.language", typeof(language).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chinese.
        /// </summary>
        internal static string chi {
            get {
                return ResourceManager.GetString("chi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to english.
        /// </summary>
        internal static string eng {
            get {
                return ResourceManager.GetString("eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frensh.
        /// </summary>
        internal static string fre {
            get {
                return ResourceManager.GetString("fre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to german.
        /// </summary>
        internal static string ger {
            get {
                return ResourceManager.GetString("ger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to italian.
        /// </summary>
        internal static string ita {
            get {
                return ResourceManager.GetString("ita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to japanese.
        /// </summary>
        internal static string jpn {
            get {
                return ResourceManager.GetString("jpn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to polish.
        /// </summary>
        internal static string pol {
            get {
                return ResourceManager.GetString("pol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to portuguese.
        /// </summary>
        internal static string por {
            get {
                return ResourceManager.GetString("por", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to russian.
        /// </summary>
        internal static string rus {
            get {
                return ResourceManager.GetString("rus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other.
        /// </summary>
        internal static string sonstig {
            get {
                return ResourceManager.GetString("sonstig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spanish.
        /// </summary>
        internal static string spa {
            get {
                return ResourceManager.GetString("spa", resourceCulture);
            }
        }
    }
}
