//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace picibird.hbs.resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class medium {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal medium() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("picibird.hbs.resources.medium", typeof(medium).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to article.
        /// </summary>
        internal static string article {
            get {
                return ResourceManager.GetString("article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to audio.
        /// </summary>
        internal static string audio {
            get {
                return ResourceManager.GetString("audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book.
        /// </summary>
        internal static string book {
            get {
                return ResourceManager.GetString("book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter.
        /// </summary>
        internal static string bookchapter {
            get {
                return ResourceManager.GetString("bookchapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        internal static string bookreview {
            get {
                return ResourceManager.GetString("bookreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Medium.
        /// </summary>
        internal static string datamed {
            get {
                return ResourceManager.GetString("datamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dissertation.
        /// </summary>
        internal static string diss {
            get {
                return ResourceManager.GetString("diss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ebook.
        /// </summary>
        internal static string ebook {
            get {
                return ResourceManager.GetString("ebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ejournal.
        /// </summary>
        internal static string ejournal {
            get {
                return ResourceManager.GetString("ejournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to journal.
        /// </summary>
        internal static string journal {
            get {
                return ResourceManager.GetString("journal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to map.
        /// </summary>
        internal static string map {
            get {
                return ResourceManager.GetString("map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other.
        /// </summary>
        internal static string other {
            get {
                return ResourceManager.GetString("other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceeding.
        /// </summary>
        internal static string proceeding {
            get {
                return ResourceManager.GetString("proceeding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to video.
        /// </summary>
        internal static string video {
            get {
                return ResourceManager.GetString("video", resourceCulture);
            }
        }
    }
}
